### ISSUE TITLE
Exception  on autotune?

### ISSUE THREAD

**Issue by GoNzCiD** [aendle/custom_components#16]
Hi, I've this exceptionin ha log. I think this is related with auto-tune option maybe?
```
2020-10-06 02:35:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_thermostat/climate.py", line 433, in _async_control_heating
    await self.calc_output()
  File "/config/custom_components/smart_thermostat/climate.py", line 475, in calc_output
    if self.pidAutotune.run(self._cur_temp):
  File "/config/custom_components/smart_thermostat/pid_controller/__init__.py", line 286, in run
    amplitude_dev = ((0.5 * (abs_max - abs_min) - self._induced_amplitude)
ZeroDivisionError: float division by zero
```

This is the configuration:
```
  - platform: smart_thermostat
    name: Pid Study
    heater: input_boolean.thermostat
    target_sensor: sensor.beca_temperature
    min_temp: 15
    max_temp: 23
    ac_mode: False
    target_temp: 18.3
    keep_alive:
      seconds: 5
    pwm : 10
    autotune : ziegler-nichols
    noiseband : 0.5
```

Thanks

**Comment by HeimdallMidgard** [comment]
Hey, i have the same error. Did you find any solution?

**Comment by GoNzCiD** [comment]
> 
> 
> Hey, i have the same error. Did you find any solution?

Unfortunately, not :(

**Comment by aendle** [comment]
I'm reworking the autotune feature at the moment.
